wandb_version: 1

batch_size:
  value: 64
epochs:
  value: 5
lr:
  value: 0.001
p_both:
  value: 0.3
p_cifar_error:
  value: 0
p_mnist_error:
  value: 0
r_mnist_to_cifar:
  value: 0.3
seed:
  value: 2
