wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.8
    start_time: 1680000505.771084
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.8
      5: 0.13.11
      8:
      - 5
batch_size:
  desc: null
  value: 64
epochs:
  desc: null
  value: 5
learning_rate:
  desc: null
  value: 0.001
p_both:
  desc: null
  value: 0.3
p_cifar_error:
  desc: null
  value: 0
p_mnist_error:
  desc: null
  value: 0
r_mnist_to_cifar:
  desc: null
  value: 0.3
seed:
  desc: null
  value: 0
